title: Elytra Blog
description: >- # this means to ignore newlines until "baseurl:"
  Elytra is the simple and  RSS Reader. This blog publishes release notes, engineering and design details.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.elytra.app"

twitter_username: 
github_username: elytraapp

author:
  name: Nikhil Nigade
  url: https://dezinezync.com
  
repo:
  url: https://github.com/elytraapp/blog.elytra.app  

icon: /assets/images/icons/web/preview_300.png
favicon: /assets/icons/favicon.png
theme_color: "#fff"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: compressed

defaults:
- scope:
    path: ""
    type: pages
  values:
    layout: default
- scope:
    path: ""
    type: posts
  values:
    layout: post
- scope:
    path: ""
    type: drafts
  values:
    layout: post

plugins:
  - jekyll-feed

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- README.md
- thanks.md
